// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 应用结构体（作为 Wails v3 Service）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckPermissions 检查系统权限
 * @returns {$CancellablePromise<$models.PermissionsInfo>}
 */
export function CheckPermissions() {
    return $Call.ByName("main.App.CheckPermissions").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Connect 连接到服务器
 * @param {string} serverURL
 * @param {string} accessKey
 * @param {string} secretKey
 * @returns {$CancellablePromise<$models.ConnectResult>}
 */
export function Connect(serverURL, accessKey, secretKey) {
    return $Call.ByName("main.App.Connect", serverURL, accessKey, secretKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Disconnect 断开连接
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByName("main.App.Disconnect");
}

/**
 * GetLogs 获取日志
 * @param {number} count
 * @returns {$CancellablePromise<$models.LogEntry[]>}
 */
export function GetLogs(count) {
    return $Call.ByName("main.App.GetLogs", count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetOCRPluginStatus 获取 OCR 插件状态
 * @returns {$CancellablePromise<$models.OCRPluginStatusResult>}
 */
export function GetOCRPluginStatus() {
    return $Call.ByName("main.App.GetOCRPluginStatus").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetStatus 获取连接状态
 * @returns {$CancellablePromise<$models.StatusResult>}
 */
export function GetStatus() {
    return $Call.ByName("main.App.GetStatus").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSystemInfo 获取系统信息
 * @returns {$CancellablePromise<$models.SystemInfo>}
 */
export function GetSystemInfo() {
    return $Call.ByName("main.App.GetSystemInfo").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * HideWindow 隐藏窗口
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByName("main.App.HideWindow");
}

/**
 * InstallOCRPlugin 安装 OCR 插件
 * @returns {$CancellablePromise<void>}
 */
export function InstallOCRPlugin() {
    return $Call.ByName("main.App.InstallOCRPlugin");
}

/**
 * LoadConfig 加载配置
 * @returns {$CancellablePromise<$models.ConfigData>}
 */
export function LoadConfig() {
    return $Call.ByName("main.App.LoadConfig").then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenAccessibilitySettings 打开辅助功能设置
 * @returns {$CancellablePromise<void>}
 */
export function OpenAccessibilitySettings() {
    return $Call.ByName("main.App.OpenAccessibilitySettings");
}

/**
 * OpenScreenRecordingSettings 打开屏幕录制设置
 * @returns {$CancellablePromise<void>}
 */
export function OpenScreenRecordingSettings() {
    return $Call.ByName("main.App.OpenScreenRecordingSettings");
}

/**
 * QuitApp 退出应用
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByName("main.App.QuitApp");
}

/**
 * SaveConfig 保存配置
 * @param {$models.ConfigData} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(data) {
    return $Call.ByName("main.App.SaveConfig", data);
}

/**
 * ShowWindow 显示窗口
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByName("main.App.ShowWindow");
}

/**
 * UninstallOCRPlugin 卸载 OCR 插件
 * @returns {$CancellablePromise<void>}
 */
export function UninstallOCRPlugin() {
    return $Call.ByName("main.App.UninstallOCRPlugin");
}

// Private type creation functions
const $$createType0 = $models.PermissionsInfo.createFrom;
const $$createType1 = $models.ConnectResult.createFrom;
const $$createType2 = $models.LogEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.OCRPluginStatusResult.createFrom;
const $$createType5 = $models.StatusResult.createFrom;
const $$createType6 = $models.SystemInfo.createFrom;
const $$createType7 = $models.ConfigData.createFrom;
