// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigData 配置数据
 */
export class ConfigData {
    /**
     * Creates a new ConfigData instance.
     * @param {Partial<ConfigData>} [$$source = {}] - The source object to create the ConfigData.
     */
    constructor($$source = {}) {
        if (!("server_url" in $$source)) {
            /**
             * 连接设置
             * @member
             * @type {string}
             */
            this["server_url"] = "";
        }
        if (!("access_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access_key"] = "";
        }
        if (!("secret_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secret_key"] = "";
        }
        if (!("auto_connect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_connect"] = false;
        }
        if (!("auto_reconnect" in $$source)) {
            /**
             * 重连设置
             * @member
             * @type {boolean}
             */
            this["auto_reconnect"] = false;
        }
        if (!("reconnect_interval" in $$source)) {
            /**
             * 秒
             * @member
             * @type {number}
             */
            this["reconnect_interval"] = 0;
        }
        if (!("log_level" in $$source)) {
            /**
             * 日志设置
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("minimize_to_tray" in $$source)) {
            /**
             * 界面设置
             * @member
             * @type {boolean}
             */
            this["minimize_to_tray"] = false;
        }
        if (!("start_minimized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["start_minimized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigData(/** @type {Partial<ConfigData>} */($$parsedSource));
    }
}

/**
 * ConnectResult 连接结果
 */
export class ConnectResult {
    /**
     * Creates a new ConnectResult instance.
     * @param {Partial<ConnectResult>} [$$source = {}] - The source object to create the ConnectResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (!("agent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectResult(/** @type {Partial<ConnectResult>} */($$parsedSource));
    }
}

/**
 * LogEntry 日志条目
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * OCRPluginStatusResult OCR 插件状态
 */
export class OCRPluginStatusResult {
    /**
     * Creates a new OCRPluginStatusResult instance.
     * @param {Partial<OCRPluginStatusResult>} [$$source = {}] - The source object to create the OCRPluginStatusResult.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OCRPluginStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OCRPluginStatusResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OCRPluginStatusResult(/** @type {Partial<OCRPluginStatusResult>} */($$parsedSource));
    }
}

/**
 * PermissionsInfo 权限信息
 */
export class PermissionsInfo {
    /**
     * Creates a new PermissionsInfo instance.
     * @param {Partial<PermissionsInfo>} [$$source = {}] - The source object to create the PermissionsInfo.
     */
    constructor($$source = {}) {
        if (!("accessibility" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accessibility"] = false;
        }
        if (!("screen_recording" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["screen_recording"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionsInfo(/** @type {Partial<PermissionsInfo>} */($$parsedSource));
    }
}

/**
 * StatusResult 状态结果
 */
export class StatusResult {
    /**
     * Creates a new StatusResult instance.
     * @param {Partial<StatusResult>} [$$source = {}] - The source object to create the StatusResult.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (!("agent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusResult(/** @type {Partial<StatusResult>} */($$parsedSource));
    }
}

/**
 * SystemInfo 系统信息
 */
export class SystemInfo {
    /**
     * Creates a new SystemInfo instance.
     * @param {Partial<SystemInfo>} [$$source = {}] - The source object to create the SystemInfo.
     */
    constructor($$source = {}) {
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemInfo(/** @type {Partial<SystemInfo>} */($$parsedSource));
    }
}
