version: '3'

vars:
  APP_NAME: "ZoeyWorker"
  GUI_DIR: "cmd/zoeyworker-gui"
  BIN_DIR: "cmd/zoeyworker-gui/bin"

env:
  CGO_ENABLED: "1"
  CGO_CFLAGS: "-IC:/opencv-minimal/include"
  CGO_CPPFLAGS: "-IC:/opencv-minimal/include"
  CGO_CXXFLAGS: "-IC:/opencv-minimal/include"
  CGO_LDFLAGS: "-LC:/opencv-minimal/x64/mingw/lib -lopencv_core4100 -lopencv_imgproc4100 -lopencv_imgcodecs4100 -lopencv_features2d4100 -lopencv_flann4100 -lopencv_calib3d4100 -lopencv_objdetect4100 -lopencv_dnn4100 -lopencv_video4100 -lopencv_photo4100 -lopencv_highgui4100 -lopencv_videoio4100"

tasks:
  default:
    cmds:
      - task: build

  frontend:build:
    desc: Copy frontend files to dist
    cmds:
      - cmd: powershell -Command "New-Item -ItemType Directory -Path '{{.GUI_DIR}}/frontend/dist' -Force | Out-Null; Copy-Item '{{.GUI_DIR}}/frontend/index.html' '{{.GUI_DIR}}/frontend/dist/' -Force; Copy-Item '{{.GUI_DIR}}/frontend/app.js' '{{.GUI_DIR}}/frontend/dist/' -Force"
        platforms: [windows]
      - cmd: mkdir -p {{.GUI_DIR}}/frontend/dist && cp {{.GUI_DIR}}/frontend/index.html {{.GUI_DIR}}/frontend/dist/ && cp {{.GUI_DIR}}/frontend/app.js {{.GUI_DIR}}/frontend/dist/
        platforms: [darwin, linux]

  frontend:dev:
    desc: Start frontend static file server for dev mode
    cmds:
      - npx -y serve {{.GUI_DIR}}/frontend -l {{.WAILS_VITE_PORT | default "9245"}} --no-clipboard

  copy-dlls:
    desc: Copy required DLLs to bin directory (Windows only)
    platforms: [windows]
    cmds:
      - cp /c/opencv-minimal/x64/mingw/bin/libopencv_*.dll {{.BIN_DIR}}/ 2>/dev/null || true
      - cp /c/msys64/mingw64/bin/libgcc_s_seh-1.dll {{.BIN_DIR}}/ 2>/dev/null || true
      - cp /c/msys64/mingw64/bin/libstdc++-6.dll {{.BIN_DIR}}/ 2>/dev/null || true
      - cp /c/msys64/mingw64/bin/libwinpthread-1.dll {{.BIN_DIR}}/ 2>/dev/null || true
      - cp /c/msys64/mingw64/bin/libgomp-1.dll {{.BIN_DIR}}/ 2>/dev/null || true
    status:
      - test -f {{.BIN_DIR}}/libgcc_s_seh-1.dll

  build:
    desc: Build the GUI application
    cmds:
      - task: frontend:build
      - cmd: powershell -Command "New-Item -ItemType Directory -Path '{{.BIN_DIR}}' -Force | Out-Null"
        platforms: [windows]
      - cmd: mkdir -p {{.BIN_DIR}}
        platforms: [darwin, linux]
      - cmd: go build -tags customenv -o {{.BIN_DIR}}/{{.APP_NAME}}.exe ./{{.GUI_DIR}}
        platforms: [windows]
      - cmd: go build -tags customenv -o {{.BIN_DIR}}/{{.APP_NAME}} ./{{.GUI_DIR}}
        platforms: [darwin, linux]
      - task: copy-dlls

  run:
    desc: Run the application
    cmds:
      - cmd: "{{.BIN_DIR}}/{{.APP_NAME}}.exe"
        platforms: [windows]
      - cmd: ./{{.BIN_DIR}}/{{.APP_NAME}}
        platforms: [darwin, linux]

  dev:
    desc: Run in development mode (wails3 hot reload, watches entire project)
    cmds:
      - wails3 dev -config ./build/config.yml

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: powershell -Command "Remove-Item -Path '{{.BIN_DIR}}' -Recurse -Force -ErrorAction SilentlyContinue"
        platforms: [windows]
      - cmd: rm -rf {{.BIN_DIR}}
        platforms: [darwin, linux]
