// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPermissions():Promise<main.PermissionInfo>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<main.ConnectResult>;

export function Disconnect():Promise<void>;

export function GetLogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetOCRPluginStatus():Promise<main.OCRPluginStatus>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function HideWindow():Promise<void>;

export function InstallOCRPlugin():Promise<void>;

export function LoadConfig():Promise<main.ConfigData>;

export function OpenAccessibilitySettings():Promise<void>;

export function OpenScreenRecordingSettings():Promise<void>;

export function QuitApp():Promise<void>;

export function RequestAccessibilityPermission():Promise<boolean>;

export function SaveConfig(arg1:main.ConfigData):Promise<void>;

export function ShowWindow():Promise<void>;

export function UninstallOCRPlugin():Promise<void>;
