// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetOCRPluginStatus() {
  return window['go']['main']['App']['GetOCRPluginStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallOCRPlugin() {
  return window['go']['main']['App']['InstallOCRPlugin']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenAccessibilitySettings() {
  return window['go']['main']['App']['OpenAccessibilitySettings']();
}

export function OpenScreenRecordingSettings() {
  return window['go']['main']['App']['OpenScreenRecordingSettings']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UninstallOCRPlugin() {
  return window['go']['main']['App']['UninstallOCRPlugin']();
}
