// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3)
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']()
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1)
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']()
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']()
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']()
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1)
}
