version: '3'

vars:
  APP_NAME: "ZoeyWorker"
  APP_NAME_LOWERCASE: "zoeyworker"
  OUTPUT_NAME: "{{.APP_NAME}}"
  GO_BUILD_FLAGS: "-ldflags '-s -w'"

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the application
    deps:
      - generate-icons
    cmds:
      - go build {{.GO_BUILD_FLAGS}} -o {{.OUTPUT_NAME}} .

  build:darwin:
    desc: Build for macOS
    cmds:
      - task: build
      - task: package:darwin

  build:windows:
    desc: Build for Windows
    vars:
      OUTPUT_NAME: "{{.APP_NAME}}.exe"
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build {{.GO_BUILD_FLAGS}} -o {{.OUTPUT_NAME}} .

  package:darwin:
    desc: Package macOS app bundle
    vars:
      APP_BUNDLE: "build/bin/{{.APP_NAME}}.app"
    cmds:
      - mkdir -p "{{.APP_BUNDLE}}/Contents/MacOS"
      - mkdir -p "{{.APP_BUNDLE}}/Contents/Resources"
      - cp {{.OUTPUT_NAME}} "{{.APP_BUNDLE}}/Contents/MacOS/"
      - |
        cat > "{{.APP_BUNDLE}}/Contents/Info.plist" << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>{{.APP_NAME}}</string>
            <key>CFBundleIdentifier</key>
            <string>com.zoey.worker</string>
            <key>CFBundleName</key>
            <string>{{.APP_NAME}}</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>CFBundleIconFile</key>
            <string>iconfile</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>LSUIElement</key>
            <false/>
        </dict>
        </plist>
        EOF
      - cp build/appicon.png "{{.APP_BUNDLE}}/Contents/Resources/iconfile.icns" 2>/dev/null || true

  generate-icons:
    desc: Generate application icons
    cmds:
      - echo "Icons are embedded in the binary"

  dev:
    desc: Run in development mode
    cmds:
      - go build -o {{.OUTPUT_NAME}} . && ./{{.OUTPUT_NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.OUTPUT_NAME}} {{.APP_NAME}}.exe
      - rm -rf build/bin
