version: '1.0'
name: build-zoeyworker
displayName: Build ZoeyWorker
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build-macos
    displayName: Build macOS
    strategy: naturally
    trigger: auto
    executor:
      type: osx
      version: latest
    steps:
      - step: shell@1
        displayName: Install Dependencies
        script: |
          brew install cmake ninja pkg-config jpeg-turbo libpng libtiff webp openjpeg zlib || true
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - step: shell@1
        displayName: Download OpenCV
        script: |
          OPENCV_VERSION="4.10.0"
          curl -sL "https://github.com/opencv/opencv/archive/refs/tags/${OPENCV_VERSION}.tar.gz" | tar xz
          curl -sL "https://github.com/opencv/opencv_contrib/archive/refs/tags/${OPENCV_VERSION}.tar.gz" | tar xz
      - step: shell@1
        displayName: Build OpenCV
        script: |
          OPENCV_VERSION="4.10.0"
          mkdir -p opencv-${OPENCV_VERSION}/build
          cd opencv-${OPENCV_VERSION}/build
          cmake .. -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$HOME/opencv-minimal \
            -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
            -DBUILD_LIST=core,imgproc,imgcodecs,features2d,flann,calib3d,xfeatures2d \
            -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF \
            -DWITH_AVFOUNDATION=OFF -DWITH_VTK=OFF -DWITH_OPENGL=OFF -DWITH_OPENCL=OFF \
            -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_LAPACK=OFF \
            -DBUILD_opencv_apps=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_videoio=OFF \
            -DBUILD_opencv_viz=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python2=OFF \
            -DBUILD_opencv_java=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF \
            -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_SHARED_LIBS=ON \
            -DBUILD_ZLIB=OFF -DBUILD_PNG=OFF -DBUILD_JPEG=OFF -DBUILD_TIFF=OFF \
            -DBUILD_WEBP=OFF -DBUILD_OPENJPEG=OFF -DBUILD_OPENEXR=OFF \
            -DOPENCV_GENERATE_PKGCONFIG=OFF
          ninja -j$(sysctl -n hw.ncpu)
          ninja install
          mkdir -p $HOME/opencv-minimal/lib/pkgconfig
          echo 'prefix=${pcfiledir}/../..' > $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'exec_prefix=${prefix}' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'libdir=${exec_prefix}/lib' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'includedir=${prefix}/include/opencv4' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo '' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'Name: OpenCV' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'Description: Open Source Computer Vision Library' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'Version: 4.10.0' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'Libs: -L${libdir} -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_calib3d -lopencv_xfeatures2d' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
          echo 'Cflags: -I${includedir}' >> $HOME/opencv-minimal/lib/pkgconfig/opencv4.pc
      - step: shell@1
        displayName: Download ONNX Runtime
        script: |
          ONNX_VERSION="1.19.2"
          curl -sL "https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/onnxruntime-osx-arm64-${ONNX_VERSION}.tgz" | tar xz
          mv onnxruntime-osx-arm64-${ONNX_VERSION} onnxruntime
          mkdir -p models
          git clone --depth 1 https://huggingface.co/getcharzp/go-ocr models/go-ocr-models || true
          if [ -d "models/go-ocr-models" ]; then
            mv models/go-ocr-models/* models/
            rm -rf models/go-ocr-models
          fi
      - step: shell@1
        displayName: Build CLI
        script: |
          export PKG_CONFIG_PATH="$HOME/opencv-minimal/lib/pkgconfig"
          export CGO_CPPFLAGS="-I$HOME/opencv-minimal/include/opencv4"
          export CGO_LDFLAGS="-L$HOME/opencv-minimal/lib -Wl,-rpath,@executable_path/../Frameworks"
          mkdir -p dist
          go build -ldflags "-s -w" -o dist/zoeyworker ./cmd/zoeyworker
      - step: shell@1
        displayName: Build GUI
        script: |
          export PKG_CONFIG_PATH="$HOME/opencv-minimal/lib/pkgconfig"
          export CGO_CPPFLAGS="-I$HOME/opencv-minimal/include/opencv4"
          export CGO_LDFLAGS="-L$HOME/opencv-minimal/lib -Wl,-rpath,@executable_path/../Frameworks"
          cd cmd/zoeyworker-gui
          wails build -ldflags "-s -w" -clean
      - step: shell@1
        displayName: Package App
        script: |
          APP_BUNDLE="cmd/zoeyworker-gui/build/bin/ZoeyWorker.app"
          FRAMEWORKS_DIR="${APP_BUNDLE}/Contents/Frameworks"
          RESOURCES_DIR="${APP_BUNDLE}/Contents/Resources"
          EXECUTABLE="${APP_BUNDLE}/Contents/MacOS/ZoeyWorker"
          OPENCV_PREFIX="$HOME/opencv-minimal"
          mkdir -p "${FRAMEWORKS_DIR}" "${RESOURCES_DIR}/models"
          cp onnxruntime/lib/*.dylib "${FRAMEWORKS_DIR}/"
          for dylib in ${OPENCV_PREFIX}/lib/*.dylib; do
            [ -f "$dylib" ] && [ ! -L "$dylib" ] && cp "$dylib" "${FRAMEWORKS_DIR}/"
          done
          for round in 1 2 3 4 5; do
            changed=0
            for dylib in "${FRAMEWORKS_DIR}"/*.dylib; do
              [ ! -f "$dylib" ] && continue
              for dep in $(otool -L "$dylib" 2>/dev/null | grep -E "/opt/homebrew|/usr/local|@rpath" | awk '{print $1}'); do
                depname=$(basename "$dep")
                if [ ! -f "${FRAMEWORKS_DIR}/${depname}" ]; then
                  if [[ "$dep" == @rpath* ]]; then
                    found_lib=$(find /opt/homebrew -name "${depname}" 2>/dev/null | head -1)
                  else
                    found_lib="$dep"
                  fi
                  if [ -n "$found_lib" ] && [ -f "$found_lib" ]; then
                    cp -L "$found_lib" "${FRAMEWORKS_DIR}/"
                    changed=1
                  fi
                fi
              done
            done
            [ $changed -eq 0 ] && break
          done
          for dep in $(otool -L "$EXECUTABLE" 2>/dev/null | grep -E "/opt/homebrew|/usr/local|$HOME|@rpath" | awk '{print $1}'); do
            libname=$(basename "$dep")
            [ -f "${FRAMEWORKS_DIR}/${libname}" ] && install_name_tool -change "$dep" "@executable_path/../Frameworks/${libname}" "$EXECUTABLE" 2>/dev/null || true
          done
          for dylib in "${FRAMEWORKS_DIR}"/*.dylib; do
            [ ! -f "$dylib" ] && continue
            libname=$(basename "$dylib")
            install_name_tool -id "@executable_path/../Frameworks/${libname}" "$dylib" 2>/dev/null || true
            for dep in $(otool -L "$dylib" 2>/dev/null | grep -E "@rpath|/opt/homebrew|/usr/local|$HOME" | awk '{print $1}'); do
              depname=$(basename "$dep")
              [ -f "${FRAMEWORKS_DIR}/${depname}" ] && install_name_tool -change "$dep" "@executable_path/../Frameworks/${depname}" "$dylib" 2>/dev/null || true
            done
          done
          cp -r models/* "${RESOURCES_DIR}/models/" 2>/dev/null || true
          codesign --force --deep --sign - "$APP_BUNDLE" 2>/dev/null || true
          mkdir -p dist
          mv "$APP_BUNDLE" dist/
          mv dist/zoeyworker dist/ZoeyWorker.app/Contents/MacOS/zoeyworker-cli
          cd dist
          zip -r ZoeyWorker-darwin-arm64.zip ZoeyWorker.app
          rm -rf ZoeyWorker.app
      - step: publish@1
        displayName: Upload Artifact
        inputs:
          artifact: ZoeyWorker-darwin-arm64
          path: dist/ZoeyWorker-darwin-arm64.zip

  - name: build-windows
    displayName: Build Windows
    strategy: naturally
    trigger: auto
    executor:
      type: windows
      version: latest
    steps:
      - step: shell@1
        displayName: Setup Environment
        script: |
          choco install mingw cmake ninja golang -y
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - step: shell@1
        displayName: Build and Package
        script: |
          echo "Windows build - requires MSYS2 environment"
          echo "This step needs to be configured based on Gitee Windows runner capabilities"
