// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_SUCCESS     TaskStatus = 1 // 成功
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 2 // 失败
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 3 // 取消
	TaskStatus_TASK_STATUS_TIMEOUT     TaskStatus = 4 // 超时
	TaskStatus_TASK_STATUS_SKIPPED     TaskStatus = 5 // 跳过
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_SUCCESS",
		2: "TASK_STATUS_FAILED",
		3: "TASK_STATUS_CANCELLED",
		4: "TASK_STATUS_TIMEOUT",
		5: "TASK_STATUS_SKIPPED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_SUCCESS":     1,
		"TASK_STATUS_FAILED":      2,
		"TASK_STATUS_CANCELLED":   3,
		"TASK_STATUS_TIMEOUT":     4,
		"TASK_STATUS_SKIPPED":     5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// 失败原因（当 status=FAILED 时）
type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED      FailureReason = 0
	FailureReason_FAILURE_REASON_NOT_FOUND        FailureReason = 1 // 图像/文字/元素未找到
	FailureReason_FAILURE_REASON_MULTIPLE_MATCHES FailureReason = 2 // 匹配到多个目标
	FailureReason_FAILURE_REASON_ASSERTION_FAILED FailureReason = 3 // 断言失败
	FailureReason_FAILURE_REASON_PARAM_ERROR      FailureReason = 4 // 参数错误
	FailureReason_FAILURE_REASON_SYSTEM_ERROR     FailureReason = 5 // 系统错误（权限、IO 等）
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_REASON_UNSPECIFIED",
		1: "FAILURE_REASON_NOT_FOUND",
		2: "FAILURE_REASON_MULTIPLE_MATCHES",
		3: "FAILURE_REASON_ASSERTION_FAILED",
		4: "FAILURE_REASON_PARAM_ERROR",
		5: "FAILURE_REASON_SYSTEM_ERROR",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED":      0,
		"FAILURE_REASON_NOT_FOUND":        1,
		"FAILURE_REASON_MULTIPLE_MATCHES": 2,
		"FAILURE_REASON_ASSERTION_FAILED": 3,
		"FAILURE_REASON_PARAM_ERROR":      4,
		"FAILURE_REASON_SYSTEM_ERROR":     5,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SystemInfo    *SystemInfo            `protobuf:"bytes,3,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *ConnectRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *ConnectRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // WINDOWS, LINUX, MACOS
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SystemInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResourceInfo  *ResourceInfo          `protobuf:"bytes,3,opt,name=resource_info,json=resourceInfo,proto3" json:"resource_info,omitempty"`
	AgentStatus   *AgentStatus           `protobuf:"bytes,4,opt,name=agent_status,json=agentStatus,proto3" json:"agent_status,omitempty"` // Agent 执行状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetResourceInfo() *ResourceInfo {
	if x != nil {
		return x.ResourceInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetAgentStatus() *AgentStatus {
	if x != nil {
		return x.AgentStatus
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float32                `protobuf:"fixed32,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceInfo) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceInfo) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceInfo) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

// Agent 执行状态
type AgentStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                   // IDLE, BUSY, PAUSED
	CurrentTaskId     string                 `protobuf:"bytes,2,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`              // 当前执行的任务 ID（空表示空闲）
	CurrentTaskType   string                 `protobuf:"bytes,3,opt,name=current_task_type,json=currentTaskType,proto3" json:"current_task_type,omitempty"`        // 当前任务类型
	TaskStartedAt     int64                  `protobuf:"varint,4,opt,name=task_started_at,json=taskStartedAt,proto3" json:"task_started_at,omitempty"`             // 任务开始时间戳
	RunningTasksCount int32                  `protobuf:"varint,5,opt,name=running_tasks_count,json=runningTasksCount,proto3" json:"running_tasks_count,omitempty"` // 运行中的任务数量
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatus) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *AgentStatus) GetCurrentTaskType() string {
	if x != nil {
		return x.CurrentTaskType
	}
	return ""
}

func (x *AgentStatus) GetTaskStartedAt() int64 {
	if x != nil {
		return x.TaskStartedAt
	}
	return 0
}

func (x *AgentStatus) GetRunningTasksCount() int32 {
	if x != nil {
		return x.RunningTasksCount
	}
	return 0
}

// 服务端 -> Worker 消息
type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_ExecuteTask
	//	*ServerMessage_CancelTask
	//	*ServerMessage_Ping
	//	*ServerMessage_DataRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ServerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetExecuteTask() *ExecuteTaskCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteTask); ok {
			return x.ExecuteTask
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelTask() *CancelTaskCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetDataRequest() *DataRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_DataRequest); ok {
			return x.DataRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_ExecuteTask struct {
	ExecuteTask *ExecuteTaskCommand `protobuf:"bytes,10,opt,name=execute_task,json=executeTask,proto3,oneof"`
}

type ServerMessage_CancelTask struct {
	CancelTask *CancelTaskCommand `protobuf:"bytes,11,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *PingCommand `protobuf:"bytes,20,opt,name=ping,proto3,oneof"`
}

type ServerMessage_DataRequest struct {
	DataRequest *DataRequest `protobuf:"bytes,30,opt,name=data_request,json=dataRequest,proto3,oneof"` // 数据查询请求
}

func (*ServerMessage_ExecuteTask) isServerMessage_Payload() {}

func (*ServerMessage_CancelTask) isServerMessage_Payload() {}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_DataRequest) isServerMessage_Payload() {}

// Worker -> 服务端 消息
type WorkerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentId   string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_TaskAck
	//	*WorkerMessage_TaskProgress
	//	*WorkerMessage_TaskResult
	//	*WorkerMessage_Pong
	//	*WorkerMessage_DataResponse
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WorkerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WorkerMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetTaskAck() *TaskAck {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskAck); ok {
			return x.TaskAck
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskProgress); ok {
			return x.TaskProgress
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *WorkerMessage) GetDataResponse() *DataResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_DataResponse); ok {
			return x.DataResponse
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_TaskAck struct {
	TaskAck *TaskAck `protobuf:"bytes,10,opt,name=task_ack,json=taskAck,proto3,oneof"`
}

type WorkerMessage_TaskProgress struct {
	TaskProgress *TaskProgress `protobuf:"bytes,11,opt,name=task_progress,json=taskProgress,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,12,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerMessage_Pong struct {
	Pong *PongResponse `protobuf:"bytes,20,opt,name=pong,proto3,oneof"`
}

type WorkerMessage_DataResponse struct {
	DataResponse *DataResponse `protobuf:"bytes,30,opt,name=data_response,json=dataResponse,proto3,oneof"` // 数据查询响应
}

func (*WorkerMessage_TaskAck) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskProgress) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Payload() {}

func (*WorkerMessage_Pong) isWorkerMessage_Payload() {}

func (*WorkerMessage_DataResponse) isWorkerMessage_Payload() {}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestType   string                 `protobuf:"bytes,1,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"` // GET_APPLICATIONS, GET_WINDOWS, GET_ELEMENTS
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON 格式的请求参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DataRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *DataRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestType   string                 `protobuf:"bytes,1,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON 格式的响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DataResponse) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *DataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type ExecuteTaskCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`          // EXECUTE_SUITE, EXECUTE_CASE, EXECUTE_STEP
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON 格式的任务参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskCommand) Reset() {
	*x = ExecuteTaskCommand{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskCommand) ProtoMessage() {}

func (x *ExecuteTaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskCommand.ProtoReflect.Descriptor instead.
func (*ExecuteTaskCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteTaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskCommand) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ExecuteTaskCommand) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type CancelTaskCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskCommand) Reset() {
	*x = CancelTaskCommand{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskCommand) ProtoMessage() {}

func (x *CancelTaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskCommand.ProtoReflect.Descriptor instead.
func (*CancelTaskCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PingCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TotalSteps      int32                  `protobuf:"varint,2,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	CompletedSteps  int32                  `protobuf:"varint,3,opt,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	PassedSteps     int32                  `protobuf:"varint,4,opt,name=passed_steps,json=passedSteps,proto3" json:"passed_steps,omitempty"`
	FailedSteps     int32                  `protobuf:"varint,5,opt,name=failed_steps,json=failedSteps,proto3" json:"failed_steps,omitempty"`
	CurrentStepName string                 `protobuf:"bytes,6,opt,name=current_step_name,json=currentStepName,proto3" json:"current_step_name,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // RUNNING, PAUSED
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *TaskProgress) GetCompletedSteps() int32 {
	if x != nil {
		return x.CompletedSteps
	}
	return 0
}

func (x *TaskProgress) GetPassedSteps() int32 {
	if x != nil {
		return x.PassedSteps
	}
	return 0
}

func (x *TaskProgress) GetFailedSteps() int32 {
	if x != nil {
		return x.FailedSteps
	}
	return 0
}

func (x *TaskProgress) GetCurrentStepName() string {
	if x != nil {
		return x.CurrentStepName
	}
	return ""
}

func (x *TaskProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 任务结果
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=zoey.agent.TaskStatus" json:"status,omitempty"` // 任务状态
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                           // 人类可读的消息
	ResultJson    string                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`   // JSON 格式的结果数据
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FailureReason FailureReason          `protobuf:"varint,7,opt,name=failure_reason,json=failureReason,proto3,enum=zoey.agent.FailureReason" json:"failure_reason,omitempty"` // 失败原因码（status=FAILED 时）
	MatchLocation *MatchLocation         `protobuf:"bytes,8,opt,name=match_location,json=matchLocation,proto3" json:"match_location,omitempty"`                                // 匹配位置（定位成功时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *TaskResult) GetMatchLocation() *MatchLocation {
	if x != nil {
		return x.MatchLocation
	}
	return nil
}

// 匹配位置信息
type MatchLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // 匹配置信度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchLocation) Reset() {
	*x = MatchLocation{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchLocation) ProtoMessage() {}

func (x *MatchLocation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchLocation.ProtoReflect.Descriptor instead.
func (*MatchLocation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *MatchLocation) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MatchLocation) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MatchLocation) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MatchLocation) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MatchLocation) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type PongResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp int64                  `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *PongResponse) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

func (x *PongResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type GetApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsRequest) Reset() {
	*x = GetApplicationsRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsRequest) ProtoMessage() {}

func (x *GetApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetApplicationsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Applications  []*ApplicationInfo     `protobuf:"bytes,3,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsResponse) Reset() {
	*x = GetApplicationsResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsResponse) ProtoMessage() {}

func (x *GetApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *GetApplicationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetApplicationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetApplicationsResponse) GetApplications() []*ApplicationInfo {
	if x != nil {
		return x.Applications
	}
	return nil
}

type ApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // 进程名称
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // 主窗口标题
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`   // 可执行文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ApplicationInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApplicationInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetWindowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"` // 可选：按进程名称筛选
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`                                   // 可选：按 PID 筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWindowsRequest) Reset() {
	*x = GetWindowsRequest{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWindowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWindowsRequest) ProtoMessage() {}

func (x *GetWindowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWindowsRequest.ProtoReflect.Descriptor instead.
func (*GetWindowsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *GetWindowsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetWindowsRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *GetWindowsRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetWindowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Windows       []*WindowInfo          `protobuf:"bytes,3,rep,name=windows,proto3" json:"windows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWindowsResponse) Reset() {
	*x = GetWindowsResponse{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWindowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWindowsResponse) ProtoMessage() {}

func (x *GetWindowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWindowsResponse.ProtoReflect.Descriptor instead.
func (*GetWindowsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *GetWindowsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWindowsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWindowsResponse) GetWindows() []*WindowInfo {
	if x != nil {
		return x.Windows
	}
	return nil
}

type WindowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`                        // 窗口句柄
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                           // 窗口标题
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`  // 窗口类名
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`                              // 所属进程 PID
	IsVisible     bool                   `protobuf:"varint,5,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"` // 是否可见
	Rect          *RectInfo              `protobuf:"bytes,6,opt,name=rect,proto3" json:"rect,omitempty"`                             // 窗口位置和大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowInfo) Reset() {
	*x = WindowInfo{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowInfo) ProtoMessage() {}

func (x *WindowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowInfo.ProtoReflect.Descriptor instead.
func (*WindowInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *WindowInfo) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *WindowInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WindowInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *WindowInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WindowInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *WindowInfo) GetRect() *RectInfo {
	if x != nil {
		return x.Rect
	}
	return nil
}

type RectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RectInfo) Reset() {
	*x = RectInfo{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectInfo) ProtoMessage() {}

func (x *RectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectInfo.ProtoReflect.Descriptor instead.
func (*RectInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *RectInfo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RectInfo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RectInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RectInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetElementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WindowHandle  int64                  `protobuf:"varint,2,opt,name=window_handle,json=windowHandle,proto3" json:"window_handle,omitempty"` // 窗口句柄
	AutomationId  string                 `protobuf:"bytes,3,opt,name=automation_id,json=automationId,proto3" json:"automation_id,omitempty"`  // 可选：按 AutomationId 筛选
	ControlType   string                 `protobuf:"bytes,4,opt,name=control_type,json=controlType,proto3" json:"control_type,omitempty"`     // 可选：按控件类型筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetElementsRequest) Reset() {
	*x = GetElementsRequest{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetElementsRequest) ProtoMessage() {}

func (x *GetElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetElementsRequest.ProtoReflect.Descriptor instead.
func (*GetElementsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *GetElementsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetElementsRequest) GetWindowHandle() int64 {
	if x != nil {
		return x.WindowHandle
	}
	return 0
}

func (x *GetElementsRequest) GetAutomationId() string {
	if x != nil {
		return x.AutomationId
	}
	return ""
}

func (x *GetElementsRequest) GetControlType() string {
	if x != nil {
		return x.ControlType
	}
	return ""
}

type GetElementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Elements      []*ElementInfo         `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetElementsResponse) Reset() {
	*x = GetElementsResponse{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetElementsResponse) ProtoMessage() {}

func (x *GetElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetElementsResponse.ProtoReflect.Descriptor instead.
func (*GetElementsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *GetElementsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetElementsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetElementsResponse) GetElements() []*ElementInfo {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ElementInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutomationId  string                 `protobuf:"bytes,1,opt,name=automation_id,json=automationId,proto3" json:"automation_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // 控件名称
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`       // 控件类名
	ControlType   string                 `protobuf:"bytes,4,opt,name=control_type,json=controlType,proto3" json:"control_type,omitempty"` // 控件类型 (Button, Edit, etc.)
	Rect          *RectInfo              `protobuf:"bytes,5,opt,name=rect,proto3" json:"rect,omitempty"`                                  // 控件位置和大小
	IsEnabled     bool                   `protobuf:"varint,6,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	IsVisible     bool                   `protobuf:"varint,7,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	Value         string                 `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"` // 控件值（如输入框内容）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementInfo) Reset() {
	*x = ElementInfo{}
	mi := &file_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementInfo) ProtoMessage() {}

func (x *ElementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementInfo.ProtoReflect.Descriptor instead.
func (*ElementInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{28}
}

func (x *ElementInfo) GetAutomationId() string {
	if x != nil {
		return x.AutomationId
	}
	return ""
}

func (x *ElementInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ElementInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ElementInfo) GetControlType() string {
	if x != nil {
		return x.ControlType
	}
	return ""
}

func (x *ElementInfo) GetRect() *RectInfo {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *ElementInfo) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *ElementInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *ElementInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\n" +
	"zoey.agent\"\x87\x01\n" +
	"\x0eConnectRequest\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x127\n" +
	"\vsystem_info\x18\x03 \x01(\v2\x16.zoey.agent.SystemInfoR\n" +
	"systemInfo\"\x7f\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\"\xa7\x01\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\"\xc6\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12=\n" +
	"\rresource_info\x18\x03 \x01(\v2\x18.zoey.agent.ResourceInfoR\fresourceInfo\x12:\n" +
	"\fagent_status\x18\x04 \x01(\v2\x17.zoey.agent.AgentStatusR\vagentStatus\"X\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"m\n" +
	"\fResourceInfo\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x02R\tdiskUsage\"\xd1\x01\n" +
	"\vAgentStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12&\n" +
	"\x0fcurrent_task_id\x18\x02 \x01(\tR\rcurrentTaskId\x12*\n" +
	"\x11current_task_type\x18\x03 \x01(\tR\x0fcurrentTaskType\x12&\n" +
	"\x0ftask_started_at\x18\x04 \x01(\x03R\rtaskStartedAt\x12.\n" +
	"\x13running_tasks_count\x18\x05 \x01(\x05R\x11runningTasksCount\"\xcb\x02\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12C\n" +
	"\fexecute_task\x18\n" +
	" \x01(\v2\x1e.zoey.agent.ExecuteTaskCommandH\x00R\vexecuteTask\x12@\n" +
	"\vcancel_task\x18\v \x01(\v2\x1d.zoey.agent.CancelTaskCommandH\x00R\n" +
	"cancelTask\x12-\n" +
	"\x04ping\x18\x14 \x01(\v2\x17.zoey.agent.PingCommandH\x00R\x04ping\x12<\n" +
	"\fdata_request\x18\x1e \x01(\v2\x17.zoey.agent.DataRequestH\x00R\vdataRequestB\t\n" +
	"\apayload\"\x91\x03\n" +
	"\rWorkerMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x120\n" +
	"\btask_ack\x18\n" +
	" \x01(\v2\x13.zoey.agent.TaskAckH\x00R\ataskAck\x12?\n" +
	"\rtask_progress\x18\v \x01(\v2\x18.zoey.agent.TaskProgressH\x00R\ftaskProgress\x129\n" +
	"\vtask_result\x18\f \x01(\v2\x16.zoey.agent.TaskResultH\x00R\n" +
	"taskResult\x12.\n" +
	"\x04pong\x18\x14 \x01(\v2\x18.zoey.agent.PongResponseH\x00R\x04pong\x12?\n" +
	"\rdata_response\x18\x1e \x01(\v2\x18.zoey.agent.DataResponseH\x00R\fdataResponseB\t\n" +
	"\apayload\"S\n" +
	"\vDataRequest\x12!\n" +
	"\frequest_type\x18\x01 \x01(\tR\vrequestType\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"\x88\x01\n" +
	"\fDataResponse\x12!\n" +
	"\frequest_type\x18\x01 \x01(\tR\vrequestType\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\"m\n" +
	"\x12ExecuteTaskCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"D\n" +
	"\x11CancelTaskCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"+\n" +
	"\vPingCommand\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"X\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfb\x01\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vtotal_steps\x18\x02 \x01(\x05R\n" +
	"totalSteps\x12'\n" +
	"\x0fcompleted_steps\x18\x03 \x01(\x05R\x0ecompletedSteps\x12!\n" +
	"\fpassed_steps\x18\x04 \x01(\x05R\vpassedSteps\x12!\n" +
	"\ffailed_steps\x18\x05 \x01(\x05R\vfailedSteps\x12*\n" +
	"\x11current_step_name\x18\x06 \x01(\tR\x0fcurrentStepName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xcf\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.zoey.agent.TaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\tR\n" +
	"resultJson\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12@\n" +
	"\x0efailure_reason\x18\a \x01(\x0e2\x19.zoey.agent.FailureReasonR\rfailureReason\x12@\n" +
	"\x0ematch_location\x18\b \x01(\v2\x19.zoey.agent.MatchLocationR\rmatchLocation\"y\n" +
	"\rMatchLocation\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"d\n" +
	"\fPongResponse\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x03R\x0fclientTimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"3\n" +
	"\x16GetApplicationsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x8e\x01\n" +
	"\x17GetApplicationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\fapplications\x18\x03 \x03(\v2\x1b.zoey.agent.ApplicationInfoR\fapplications\"a\n" +
	"\x0fApplicationInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"c\n" +
	"\x11GetWindowsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"z\n" +
	"\x12GetWindowsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\awindows\x18\x03 \x03(\v2\x16.zoey.agent.WindowInfoR\awindows\"\xb4\x01\n" +
	"\n" +
	"WindowInfo\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x05 \x01(\bR\tisVisible\x12(\n" +
	"\x04rect\x18\x06 \x01(\v2\x14.zoey.agent.RectInfoR\x04rect\"T\n" +
	"\bRectInfo\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x9c\x01\n" +
	"\x12GetElementsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rwindow_handle\x18\x02 \x01(\x03R\fwindowHandle\x12#\n" +
	"\rautomation_id\x18\x03 \x01(\tR\fautomationId\x12!\n" +
	"\fcontrol_type\x18\x04 \x01(\tR\vcontrolType\"~\n" +
	"\x13GetElementsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\belements\x18\x03 \x03(\v2\x17.zoey.agent.ElementInfoR\belements\"\x86\x02\n" +
	"\vElementInfo\x12#\n" +
	"\rautomation_id\x18\x01 \x01(\tR\fautomationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\x12!\n" +
	"\fcontrol_type\x18\x04 \x01(\tR\vcontrolType\x12(\n" +
	"\x04rect\x18\x05 \x01(\v2\x14.zoey.agent.RectInfoR\x04rect\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x06 \x01(\bR\tisEnabled\x12\x1d\n" +
	"\n" +
	"is_visible\x18\a \x01(\bR\tisVisible\x12\x14\n" +
	"\x05value\x18\b \x01(\tR\x05value*\xa7\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_SUCCESS\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_TIMEOUT\x10\x04\x12\x17\n" +
	"\x13TASK_STATUS_SKIPPED\x10\x05*\xd8\x01\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FAILURE_REASON_NOT_FOUND\x10\x01\x12#\n" +
	"\x1fFAILURE_REASON_MULTIPLE_MATCHES\x10\x02\x12#\n" +
	"\x1fFAILURE_REASON_ASSERTION_FAILED\x10\x03\x12\x1e\n" +
	"\x1aFAILURE_REASON_PARAM_ERROR\x10\x04\x12\x1f\n" +
	"\x1bFAILURE_REASON_SYSTEM_ERROR\x10\x052\xdd\x03\n" +
	"\fAgentService\x12B\n" +
	"\aConnect\x12\x1a.zoey.agent.ConnectRequest\x1a\x1b.zoey.agent.ConnectResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.zoey.agent.HeartbeatRequest\x1a\x1d.zoey.agent.HeartbeatResponse\x12F\n" +
	"\n" +
	"TaskStream\x12\x19.zoey.agent.WorkerMessage\x1a\x19.zoey.agent.ServerMessage(\x010\x01\x12Z\n" +
	"\x0fGetApplications\x12\".zoey.agent.GetApplicationsRequest\x1a#.zoey.agent.GetApplicationsResponse\x12K\n" +
	"\n" +
	"GetWindows\x12\x1d.zoey.agent.GetWindowsRequest\x1a\x1e.zoey.agent.GetWindowsResponse\x12N\n" +
	"\vGetElements\x12\x1e.zoey.agent.GetElementsRequest\x1a\x1f.zoey.agent.GetElementsResponseb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_agent_proto_goTypes = []any{
	(TaskStatus)(0),                 // 0: zoey.agent.TaskStatus
	(FailureReason)(0),              // 1: zoey.agent.FailureReason
	(*ConnectRequest)(nil),          // 2: zoey.agent.ConnectRequest
	(*ConnectResponse)(nil),         // 3: zoey.agent.ConnectResponse
	(*SystemInfo)(nil),              // 4: zoey.agent.SystemInfo
	(*HeartbeatRequest)(nil),        // 5: zoey.agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 6: zoey.agent.HeartbeatResponse
	(*ResourceInfo)(nil),            // 7: zoey.agent.ResourceInfo
	(*AgentStatus)(nil),             // 8: zoey.agent.AgentStatus
	(*ServerMessage)(nil),           // 9: zoey.agent.ServerMessage
	(*WorkerMessage)(nil),           // 10: zoey.agent.WorkerMessage
	(*DataRequest)(nil),             // 11: zoey.agent.DataRequest
	(*DataResponse)(nil),            // 12: zoey.agent.DataResponse
	(*ExecuteTaskCommand)(nil),      // 13: zoey.agent.ExecuteTaskCommand
	(*CancelTaskCommand)(nil),       // 14: zoey.agent.CancelTaskCommand
	(*PingCommand)(nil),             // 15: zoey.agent.PingCommand
	(*TaskAck)(nil),                 // 16: zoey.agent.TaskAck
	(*TaskProgress)(nil),            // 17: zoey.agent.TaskProgress
	(*TaskResult)(nil),              // 18: zoey.agent.TaskResult
	(*MatchLocation)(nil),           // 19: zoey.agent.MatchLocation
	(*PongResponse)(nil),            // 20: zoey.agent.PongResponse
	(*GetApplicationsRequest)(nil),  // 21: zoey.agent.GetApplicationsRequest
	(*GetApplicationsResponse)(nil), // 22: zoey.agent.GetApplicationsResponse
	(*ApplicationInfo)(nil),         // 23: zoey.agent.ApplicationInfo
	(*GetWindowsRequest)(nil),       // 24: zoey.agent.GetWindowsRequest
	(*GetWindowsResponse)(nil),      // 25: zoey.agent.GetWindowsResponse
	(*WindowInfo)(nil),              // 26: zoey.agent.WindowInfo
	(*RectInfo)(nil),                // 27: zoey.agent.RectInfo
	(*GetElementsRequest)(nil),      // 28: zoey.agent.GetElementsRequest
	(*GetElementsResponse)(nil),     // 29: zoey.agent.GetElementsResponse
	(*ElementInfo)(nil),             // 30: zoey.agent.ElementInfo
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: zoey.agent.ConnectRequest.system_info:type_name -> zoey.agent.SystemInfo
	7,  // 1: zoey.agent.HeartbeatRequest.resource_info:type_name -> zoey.agent.ResourceInfo
	8,  // 2: zoey.agent.HeartbeatRequest.agent_status:type_name -> zoey.agent.AgentStatus
	13, // 3: zoey.agent.ServerMessage.execute_task:type_name -> zoey.agent.ExecuteTaskCommand
	14, // 4: zoey.agent.ServerMessage.cancel_task:type_name -> zoey.agent.CancelTaskCommand
	15, // 5: zoey.agent.ServerMessage.ping:type_name -> zoey.agent.PingCommand
	11, // 6: zoey.agent.ServerMessage.data_request:type_name -> zoey.agent.DataRequest
	16, // 7: zoey.agent.WorkerMessage.task_ack:type_name -> zoey.agent.TaskAck
	17, // 8: zoey.agent.WorkerMessage.task_progress:type_name -> zoey.agent.TaskProgress
	18, // 9: zoey.agent.WorkerMessage.task_result:type_name -> zoey.agent.TaskResult
	20, // 10: zoey.agent.WorkerMessage.pong:type_name -> zoey.agent.PongResponse
	12, // 11: zoey.agent.WorkerMessage.data_response:type_name -> zoey.agent.DataResponse
	0,  // 12: zoey.agent.TaskResult.status:type_name -> zoey.agent.TaskStatus
	1,  // 13: zoey.agent.TaskResult.failure_reason:type_name -> zoey.agent.FailureReason
	19, // 14: zoey.agent.TaskResult.match_location:type_name -> zoey.agent.MatchLocation
	23, // 15: zoey.agent.GetApplicationsResponse.applications:type_name -> zoey.agent.ApplicationInfo
	26, // 16: zoey.agent.GetWindowsResponse.windows:type_name -> zoey.agent.WindowInfo
	27, // 17: zoey.agent.WindowInfo.rect:type_name -> zoey.agent.RectInfo
	30, // 18: zoey.agent.GetElementsResponse.elements:type_name -> zoey.agent.ElementInfo
	27, // 19: zoey.agent.ElementInfo.rect:type_name -> zoey.agent.RectInfo
	2,  // 20: zoey.agent.AgentService.Connect:input_type -> zoey.agent.ConnectRequest
	5,  // 21: zoey.agent.AgentService.Heartbeat:input_type -> zoey.agent.HeartbeatRequest
	10, // 22: zoey.agent.AgentService.TaskStream:input_type -> zoey.agent.WorkerMessage
	21, // 23: zoey.agent.AgentService.GetApplications:input_type -> zoey.agent.GetApplicationsRequest
	24, // 24: zoey.agent.AgentService.GetWindows:input_type -> zoey.agent.GetWindowsRequest
	28, // 25: zoey.agent.AgentService.GetElements:input_type -> zoey.agent.GetElementsRequest
	3,  // 26: zoey.agent.AgentService.Connect:output_type -> zoey.agent.ConnectResponse
	6,  // 27: zoey.agent.AgentService.Heartbeat:output_type -> zoey.agent.HeartbeatResponse
	9,  // 28: zoey.agent.AgentService.TaskStream:output_type -> zoey.agent.ServerMessage
	22, // 29: zoey.agent.AgentService.GetApplications:output_type -> zoey.agent.GetApplicationsResponse
	25, // 30: zoey.agent.AgentService.GetWindows:output_type -> zoey.agent.GetWindowsResponse
	29, // 31: zoey.agent.AgentService.GetElements:output_type -> zoey.agent.GetElementsResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_ExecuteTask)(nil),
		(*ServerMessage_CancelTask)(nil),
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_DataRequest)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*WorkerMessage_TaskAck)(nil),
		(*WorkerMessage_TaskProgress)(nil),
		(*WorkerMessage_TaskResult)(nil),
		(*WorkerMessage_Pong)(nil),
		(*WorkerMessage_DataResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
